"""create add None order product table

Revision ID: f4fb1af5a1ef
Revises: 8cdeb69b0f50
Create Date: 2025-11-06 11:38:30.837266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4fb1af5a1ef"
down_revision: Union[str, Sequence[str], None] = "8cdeb69b0f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
